apiVersion: v1
kind: Service
metadata:
    name: "myakscluster-e1f8"
    labels:
        app: "myakscluster-e1f8"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "myakscluster-e1f8"